@startuml

title __UTILS's Class Diagram__\n

  namespace com.example.paperhelper {
    namespace utils {
      class com.example.paperhelper.utils.DateUtil {
          {static} - simpleDateFormat : SimpleDateFormat
          {static} + getDateString()
      }
    }
  }
  

  namespace com.example.paperhelper {
    namespace utils {
      class com.example.paperhelper.utils.FileHelper {
          {static} - instance : FileHelper
          + getFileCreateTime()
          {static} + getInstance()
          + readFile()
          + readHtml()
          + writeFile()
          + writeFile()
          - FileHelper()
          - readFile()
      }
    }
  }
  

  namespace com.example.paperhelper {
    namespace utils {
      class com.example.paperhelper.utils.MyDownloadStart {
          ~ tipDialog : QMUITipDialog
          - activity : Activity
          - dialogBuilder : MessageDialogBuilder
          - webView : WebView
          + MyDownloadStart()
          + onDownloadStart()
          - downloadFailureShow()
          - downloadFile()
          - downloadSuccessShow()
      }
    }
  }
  

  namespace com.example.paperhelper {
    namespace utils {
      class com.example.paperhelper.utils.RequestCenter {
          {static} + downloadFileRequest()
      }
    }
  }
  

  namespace com.example.paperhelper {
    namespace utils {
      class com.example.paperhelper.utils.TestData {
          {static} + getTestFileItem()
          {static} + getTestPageUrlItem()
      }
    }
  }
  

  com.example.paperhelper.utils.MyDownloadStart .up.|> android.webkit.DownloadListener


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
