@startuml

title __BEAN's Class Diagram__\n

  namespace com.example.paperhelper {
    namespace model {
      namespace bean {
        class com.example.paperhelper.model.bean.FileItem {
            - file : File
            - fileName : String
            - image : int
            + FileItem()
            + FileItem()
            + FileItem()
            + getFile()
            + getFileName()
            + getImage()
        }
      }
    }
  }
  

  namespace com.example.paperhelper {
    namespace model {
      namespace bean {
        class com.example.paperhelper.model.bean.HtmlTest {
            - content : String
            + HtmlTest()
            + getContent()
        }
      }
    }
  }
  

  namespace com.example.paperhelper {
    namespace model {
      namespace bean {
        class com.example.paperhelper.model.bean.NotebookItem {
            - content : String
            - file_name : String
            - icon : int
            - path : String
            - time : String
            + NotebookItem()
            + getContent()
            + getFileName()
            + getIcon()
            + getPath()
            + getTime()
            + setContent()
            + setFileName()
            + setIcon()
            + setPath()
            + setTime()
        }
      }
    }
  }
  

  namespace com.example.paperhelper {
    namespace model {
      namespace bean {
        class com.example.paperhelper.model.bean.PageUrlModel {
            - id : Long
            - pageName : String
            - url : String
            + PageUrlModel()
            + PageUrlModel()
            + PageUrlModel()
            + getId()
            + getPageName()
            + getUrl()
            + setId()
            + setPageName()
            + setUrl()
        }
      }
    }
  }
  

  namespace com.example.paperhelper {
    namespace model {
      namespace bean {
        class com.example.paperhelper.model.bean.Schedule {
            - content : String
            - difficulty : String
            - duration : int
            - isFinished : boolean
            - isImportant : boolean
            - notes : String
            - time : String
            + Schedule()
            + getContent()
            + getDifficulty()
            + getDuration()
            + getNotes()
            + getTime()
            + isFinished()
            + isImportant()
            + setContent()
            + setDifficulty()
            + setDuration()
            + setFinished()
            + setImportant()
            + setNotes()
            + setTime()
        }
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
